networks:
  eventeny:
services:
  web:
    build:
      dockerfile: Dockerfile
    container_name: eventenyApp
    ports:
      - "80:80" 
    depends_on:
      - db 
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    env_file:
      - app/web.env
    networks:
      - eventeny
  db:
    image: mysql:latest
    container_name: eventenyMysql
    ports:
      - '3308:3306'
    env_file:
      - app/db.env
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - eventeny
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
    networks:
      - eventeny